### PR TITLE
Added a gh-action for first -time contributors

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
Pertains to #38 

@emmalearnscode Can you please review this PR 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EventCalendar/pull/64"></a>

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
My GitHub action knowledge is a little sketchy, I’m still learning them and mostly copy/paste, so I’m not the right person to review this pr. hopefully someone with more knowledge will take a look soon.

**Review by suitupstan — CHANGES_REQUESTED** [review]
We have a community action [here](https://github.com/EddieHubCommunity/gh-action-community/tree/develop/src/welcome). It would be better if this is used

**Comment by suitupstan** [comment]
Hey there @Jassi10000 👋 Just checking in, do you need any help?

**Comment by Jassi10000-zz** [comment]
> Hey there @Jassi10000 👋 Just checking in, do you need any help?

No buddy , just confused that should I close the PR as you are suggesting the community action or do anything else to make it better

**Comment by eddiejaoude** [comment]
@Jassi10000 we have a welcome GitHub Action already we can use, it is better to keep it consistent with our other repos https://github.com/EddieHubCommunity/gh-action-community

You can either update this PR or close this PR and create a new one

**Comment by Jassi10000-zz** [comment]
@eddiejaoude Can you give some hints on how should I improve the PR ?

**Comment by eddiejaoude** [comment]
@Jassi10000 what do you need help with? The link I shared has documentation and example usage. If you could be more specific with what you need help with then we can try to help 🤓 

The GitHub Action will look like

```yml
on:
  fork:
  push:
    branches: [ main ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community :nerd_face: :rocket:'
          pr-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community :nerd_face:'
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord</a> chat and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'
```

**Comment by Jassi10000-zz** [comment]
@eddiejaoude Can you please review the latest changes ?

**Review by Cahllagerfeld — APPROVED** [review]
LGTM 👍

**Pull request merged**
