### PR TITLE
Add margin to Calendar

### PR DESCRIPTION
**Pull request by handikaharianto**
I've added some margins around the Calendar which also fix the spacing issue below the Navbar (Issue no: #58 ).

Note: I closed the previous pull request because there was one line of code that I forgot to delete.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EventCalendar/pull/63"></a>

### CODE REVIEW

**Comment by mohan-murali** [comment]
Can you add a screenshot with the final look?

**Comment by handikaharianto** [comment]
> Can you add a screenshot with the final look?

Here is the final look.

image

**Comment by eddiejaoude** [comment]
Great collaboration 👍

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by handikaharianto** [comment]
Thank you, Eddie! This is my first contribution ever. It means a lot!

**Comment by eddiejaoude** [comment]
You are welcome 👍 keep going 🤓

**Pull request merged**
