### PR TITLE
added husky,lint staged and prettier.

### PR DESCRIPTION
**Pull request by rahulkhattri0**

### CODE REVIEW

**Review by suitupstan — COMMENTED** [review]
Why did you close this PR? 😅 Also please do not open PRs without getting the issue assigned? 🙂

**Comment by rahulkhattri0** [comment]
closed it by mistake. I'm sorry for that. Also ,I have been assinged to the husky issue.

**Comment by suitupstan** [comment]
> closed it by mistake. I'm sorry for that. Also ,I have been assinged to the husky issue.
>  

But you added linters? 😅

**Comment by rahulkhattri0** [comment]
Lint staged collects all the staged files and husky runs the pre commit hook. Prettier formats the code

**Comment by suitupstan** [comment]
> Lint staged collects all the staged files and husky runs the pre-commit hook. Prettier formats the code

isn't eslint: #41 assigned to @StarTrooper08? 🤔

**Comment by rahulkhattri0** [comment]
I have not used eslint

**Comment by suitupstan** [comment]
> I have not used eslint

your PR adds eslintConfig key to package.json

**Comment by rahulkhattri0** [comment]
I'll remove it

**Comment by rahulkhattri0** [comment]
https://github.com/EddieHubCommunity/EventCalendar/pull/71#discussion_r752342203

**Comment by rahulkhattri0** [comment]
https://github.com/EddieHubCommunity/EventCalendar/pull/71#issuecomment-973043977

**Pull request closed without merging**
