### PR TITLE
Formatted the codebase

### LINKED ISSUE #31: create docker file and publish to gh container registry

### PR DESCRIPTION
**Pull request by carrotfarmer**
## Fixes Issue
- Formatted all the JS code (double codes, spacing, indentation etc.)

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project. (I'm not sure lol)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
N/A

## Note to reviewers
Nothing

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EventCalendar/pull/87"></a>

### CODE REVIEW

**Review by suitupstan — APPROVED** [review]

**Review by Pradumnasaraf — APPROVED** [review]

**Comment by EmmaDawsonDev** [comment]
I think we should wait with this until the PRs for husky, prettier and linting are complete.

**Comment by carrotfarmer** [comment]
Yes, the linting rules may conflict.

**Review by thepranaygupta — APPROVED** [review]

**Review by vikasganiga05 — APPROVED** [review]

**Review by suitupstan — CHANGES_REQUESTED** [review]
Well I think you deleted the fork 😓

**Comment by carrotfarmer** [comment]
😂 pls check #90

**Pull request closed without merging**
