### PR TITLE
Formatted codebase

### LINKED ISSUE #31: create docker file and publish to gh container registry

### PR DESCRIPTION
**Pull request by carrotfarmer**
## Fixes Issue
- Formatted all the JS code (double quotes, spacing, indentation etc.), removed an unused import

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EventCalendar/pull/90"></a>

### CODE REVIEW

**Review by suitupstan — APPROVED** [review]

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1: 
I am new to react, why did you remove `import { Calendar } from "@fullcalendar/core";` from `src/App.js` file.

**Comment by carrotfarmer** [comment]
@vikasganiga05 I removed that import because VSCode showed that it wasn't used anywhere in the component. I may be wrong though because ESLint was disabled in the next line, but looks good so far 👀

**Comment by vikasganiga05** [comment]
> 

Oh! okay, Thanks for explaining :slightly_smiling_face:

**Comment by vikasganiga05** [comment]
> @vikasganiga05 I removed that import because VSCode showed that it wasn't used anywhere in the component. I may be wrong though because ESLint was disabled in the next line, but looks good so far eyes

Oh! okay, Thanks for explaining :slightly_smiling_face:

**Review by Pradumnasaraf — APPROVED** [review]

**Review by suitupstan — APPROVED** [review]

**Pull request closed without merging**
