### PR TITLE
feat: Add basic issue forms

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Add basic issue forms.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EventCalendar/pull/51"></a>

### CODE REVIEW

**Comment by mohan-murali** [comment]
do we need package-lock.json file in this pr?

**Comment by Panquesito7** [comment]
> do we need package-lock.json file in this pr?

Not sure. There aren't many needed changes, though.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍 

`package-lock` not needed, please remove

**Review by mohan-murali — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Pull request merged**
